name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        include:
          - python-version: '3.12'
            commit: false
          - python-version: '3.11'
            commit: false
          - python-version: '3.10'
            commit: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pytest black
          VERSION="0.0.$(date +%s)"
          sed -i "s/{{VERSION_PLACEHOLDER}}/$VERSION/" corkit/__init__.py
          pip install --no-build-isolation -e .
          python3 update.py

      - name: Run tests
        run: |
          pytest tests/
